export GZ_SIM_RESOURCE_PATH=${GZ_SIM_RESOURCE_PATH}:${CONDA_PREFIX}/share/
export GZ_SIM_SYSTEM_PLUGIN_PATH=${GZ_SIM_SYSTEM_PLUGIN_PATH}:${CONDA_PREFIX}/lib

export YARP_ROBOT_NAME="ergoCubGazeboV1_1"
export YARP_DATA_DIRS=${YARP_DATA_DIRS}:${CONDA_PREFIX}/share/ergoCub
export GAZEBO_MODEL_PATH=${GAZEBO_MODEL_PATH}:${CONDA_PREFIX}/share:${CONDA_PREFIX}/share/ergoCub/robots
# export YARP_CLOCK=/clock
